apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-apiserver-proxies
spec:
  type: kube-apiserver
  replicas: 2
  tags:
    - tag:k8s
    - tag:ehpc-io
  kubeAPIServer:
    mode: auth
