apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "ehpc.io"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ehpc-io-secret
      allowedRoutes:
        namespaces:
          from: All
    - name: https-www
      port: 443
      protocol: HTTPS
      hostname: "www.ehpc.io"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: www-ehpc-io-secret
      allowedRoutes:
        namespaces:
          from: All
    - name: grafana
      port: 8543
      protocol: HTTPS
      hostname: "grafana.ehpc.io"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: grafana-ehpc-io-secret
      allowedRoutes:
        namespaces:
          from: All
