repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: nginx
    url: ghcr.io/nginx/charts
    oci: true
  - name: prometheus-community
    url: ghcr.io/prometheus-community/charts
    oci: true
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: valkey
    url: https://valkey.io/valkey-helm/

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.19.1
    values:
      - values/cert-manager.yaml
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    values:
      - values/metallb.yaml
  - name: prometheus
    installed: true
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: ~27.47.0
    values:
      - values/prometheus.yaml
  - name: grafana
    namespace: monitoring
    chart: ./grafana-chart
  - name: ngf
    namespace: nginx-gateway
    chart: nginx/nginx-gateway-fabric
    version: ~2.2.1
    wait: true
    values:
      - values/nginx.yaml
  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    wait: true
    values:
      - values/tailscale.yaml
  - name: opentelemetry-operator
    chart: open-telemetry/opentelemetry-operator
    values:
      - values/opentelemetry-operator.yaml
  - name: valkey
    namespace: valkey
    chart: valkey/valkey
    version: ~0.8.1
    values:
      - values/valkey.yaml
  