repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: nginx
    url: ghcr.io/nginx/charts
    oci: true
  - name: prometheus-community
    url: ghcr.io/prometheus-community/charts
    oci: true
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.19.1
    values:
      - values/cert-manager.yaml
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    values:
      - values/metallb.yaml
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    values:
      - values/longhorn.yaml
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: ~27.47.0
    values:
      - values/prometheus.yaml
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: ~10.2.0
    values:
      - values/grafana.yaml
  - name: ngf
    namespace: nginx-gateway
    chart: nginx/nginx-gateway-fabric
    version: ~2.2.1
    wait: true
    values:
      - values/nginx.yaml
  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    wait: true
    values:
      - values/tailscale.yaml
