apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: www-redirect
spec:
  parentRefs:
    - name: eg
  hostnames:
    - www.ehpc.io
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: ehpc.io
            statusCode: 301
