apiVersion: v2
name: ehpc-io-grafana
description: Custom Grafana chart
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 10.2.0
