apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: compression-sf
  namespace: ehpc-io
spec:
  snippets:
    - context: http
      value: |
        gzip on;
        gzip_min_length 1024;
        gzip_types
          text/plain
          text/css
          text/xml
          text/javascript
          text/json
          application/javascript
          application/json
          application/xml
          application/xml+rss
          image/svg+xml
          font/ttf
          font/otf
          application/vnd.ms-fontobject;
